//! Stage B — cross-language determinism gate.
//!
//! Loads `tests/goldens/golden.json` (generated by
//! `cd ~/Work/Prototypes/demiurge && npx tsx tools/dump-golden.mjs`)
//! and asserts that the Rust port reproduces every demiurge golden vector
//! within the stated tolerance.
//!
//! Tolerances:
//!   - Noise3D::sample, fbm, ridged : < 1e-12 (bit-exact modulo FP reassociation)
//!   - Tectonics::query scalars      : < 1e-9
//!   - TectonicHeightField::height   : < 1e-9
//!
//! If the Rust port DIVERGES from a golden, this test reports:
//!   - which function diverged
//!   - which input vector triggered the divergence
//!   - expected vs actual value
//!   - magnitude of error
//!
//! Do NOT loosen tolerances to force a pass.
//!
//! TEETH TEST: a deliberate wrong-value assertion verifies the gate itself
//! would catch divergence (it uses assert_ne! on a perturbed value).

use std::path::PathBuf;

use glam::DVec3;
use serde::Deserialize;

use enki_planet::{
    noise::{Noise3D, fbm, ridged},
    sampler::{TectonicHeightField, TectonicHeightFieldParams},
    tectonics::Tectonics,
    climate::ClimateParams,
    height::HeightField,
};

// ---------------------------------------------------------------------------
// JSON schema (mirrors golden.json fields)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct Golden {
    params:            Params,
    noise_samples:     Vec<NoiseSample>,
    fbm_samples:       Vec<FbmRidgedSample>,
    ridged_samples:    Vec<FbmRidgedSample>,
    tectonics_samples: Vec<TectonicsSample>,
    height_samples:    Vec<HeightSample>,
}

#[derive(Debug, Deserialize)]
struct Params {
    seed:               u32,
    plate_count:        usize,
    arc_density:        f64,
    hotspot_count:      u32,
    hotspot_intensity:  f64,
    base_temp:          f64,
    atmosphere:         f64,
    band_count:         u32,
    axial_tilt_deg:     f64,
}

#[derive(Debug, Deserialize)]
struct NoiseSample {
    x: f64, y: f64, z: f64,
    value: f64,
}

#[derive(Debug, Deserialize)]
struct FbmRidgedSample {
    x: f64, y: f64, z: f64,
    octaves:    u32,
    frequency:  f64,
    lacunarity: f64,
    gain:       f64,
    value:      f64,
}

#[derive(Debug, Deserialize)]
struct TectonicsSample {
    x: f64, y: f64, z: f64,
    plate_id:         usize,
    neighbor_id:      usize,
    boundary_dist:    f64,
    convergence:      f64,
    shear:            f64,
    crust_dist:       f64,
    paleo_dist:       f64,
    other_crust_dist: f64,
}

#[derive(Debug, Deserialize)]
struct HeightSample {
    x: f64, y: f64, z: f64,
    level: u8,
    value: f64,
}

// ---------------------------------------------------------------------------
// Helper: load golden from the checked-in JSON
// ---------------------------------------------------------------------------

fn load_golden() -> Golden {
    // The test binary runs from the crate root, so paths are relative to
    // enki-planet/. The goldens directory is at tests/goldens/golden.json.
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/goldens/golden.json");

    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to read golden file {}: {}", path.display(), e));

    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("Failed to parse golden JSON: {}", e))
}

// ---------------------------------------------------------------------------
// Tolerance constants
// ---------------------------------------------------------------------------

/// Noise3D::sample, fbm, ridged: bit-exact from same algorithm; allow
/// tiny epsilon for FP reassociation in release mode.
const NOISE_TOL: f64 = 1e-12;

/// Tectonics::query scalars: blurred fields interpolated via sampleSmooth →
/// f32 storage, so f32 precision (≈6e-8) is the floor. We allow 1e-9 for
/// the Rust side to exactly match f64 accumulation before the f32 truncation.
const TECT_TOL: f64 = 1e-9;

/// TectonicHeightField::height: composed from many tectonic fields + noise.
/// End-to-end tolerance matches the tectonic tolerance.
const HEIGHT_TOL: f64 = 1e-9;

// ---------------------------------------------------------------------------
// TEETH TEST — verifies the gate would catch a 1-bit divergence
// ---------------------------------------------------------------------------

/// This test deliberately perturbs a known value and confirms assert_ne! fires.
/// It proves the gate is live, not always-pass.
#[test]
fn teeth_gate_catches_divergence() {
    let g = load_golden();
    let s = &g.noise_samples[0];
    let noise = Noise3D::new(g.params.seed);
    let actual = noise.sample(s.x, s.y, s.z);
    // The actual value must equal the golden (gate is live)
    assert!((actual - s.value).abs() < NOISE_TOL,
        "teeth test setup failed: noise doesn't match golden at sample[0]");
    // A deliberate wrong value must NOT equal actual — proves the gate would catch it.
    let wrong = actual + 1e-10;
    assert_ne!(actual.to_bits(), wrong.to_bits(),
        "teeth test broken: perturbed value is identical to actual (f64 precision issue)");
    // The gate catches it: wrong value fails the tolerance check
    let divergence = (wrong - s.value).abs();
    assert!(divergence > NOISE_TOL,
        "teeth test broken: wrong value ({}) passes tolerance {} — gate is too loose", divergence, NOISE_TOL);
}

// ---------------------------------------------------------------------------
// A. Noise3D::sample
// ---------------------------------------------------------------------------

#[test]
fn golden_noise_sample() {
    let g = load_golden();
    let noise = Noise3D::new(g.params.seed);
    let mut failures = Vec::new();

    for (i, s) in g.noise_samples.iter().enumerate() {
        let actual = noise.sample(s.x, s.y, s.z);
        let err = (actual - s.value).abs();
        if err > NOISE_TOL {
            failures.push(format!(
                "  sample[{i}] at ({x:.6},{y:.6},{z:.6}): expected {exp:.17e}, got {act:.17e}, err={err:.3e}",
                x = s.x, y = s.y, z = s.z,
                exp = s.value, act = actual,
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "FAIL: Noise3D::sample diverged from golden ({}/{} vectors):\n{}",
            failures.len(), g.noise_samples.len(),
            failures.join("\n")
        );
    }
    println!("PASS: Noise3D::sample — {} vectors within {NOISE_TOL:.0e}", g.noise_samples.len());
}

// ---------------------------------------------------------------------------
// B. fbm
// ---------------------------------------------------------------------------

#[test]
fn golden_fbm() {
    let g = load_golden();
    let noise = Noise3D::new(g.params.seed);
    let mut failures = Vec::new();

    for (i, s) in g.fbm_samples.iter().enumerate() {
        let actual = fbm(&noise, s.x, s.y, s.z, s.octaves, s.frequency, s.lacunarity, s.gain);
        let err = (actual - s.value).abs();
        if err > NOISE_TOL {
            failures.push(format!(
                "  fbm[{i}] at ({x:.6},{y:.6},{z:.6}) oct={oct}: expected {exp:.17e}, got {act:.17e}, err={err:.3e}",
                x = s.x, y = s.y, z = s.z, oct = s.octaves,
                exp = s.value, act = actual,
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "FAIL: fbm diverged from golden ({}/{} vectors):\n{}",
            failures.len(), g.fbm_samples.len(),
            failures.join("\n")
        );
    }
    println!("PASS: fbm — {} vectors within {NOISE_TOL:.0e}", g.fbm_samples.len());
}

// ---------------------------------------------------------------------------
// C. ridged
// ---------------------------------------------------------------------------

#[test]
fn golden_ridged() {
    let g = load_golden();
    let noise = Noise3D::new(g.params.seed);
    let mut failures = Vec::new();

    for (i, s) in g.ridged_samples.iter().enumerate() {
        let actual = ridged(&noise, s.x, s.y, s.z, s.octaves, s.frequency, s.lacunarity, s.gain);
        let err = (actual - s.value).abs();
        if err > NOISE_TOL {
            failures.push(format!(
                "  ridged[{i}] at ({x:.6},{y:.6},{z:.6}) oct={oct}: expected {exp:.17e}, got {act:.17e}, err={err:.3e}",
                x = s.x, y = s.y, z = s.z, oct = s.octaves,
                exp = s.value, act = actual,
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "FAIL: ridged diverged from golden ({}/{} vectors):\n{}",
            failures.len(), g.ridged_samples.len(),
            failures.join("\n")
        );
    }
    println!("PASS: ridged — {} vectors within {NOISE_TOL:.0e}", g.ridged_samples.len());
}

// ---------------------------------------------------------------------------
// D. Tectonics::query — ALL scalar fields
// ---------------------------------------------------------------------------

#[test]
fn golden_tectonics_query() {
    let g = load_golden();
    let p = &g.params;
    let tect = Tectonics::new(
        p.seed,
        p.plate_count,
        p.arc_density,
        p.hotspot_count,
        p.hotspot_intensity,
    );

    let mut failures = Vec::new();

    for (i, s) in g.tectonics_samples.iter().enumerate() {
        let dir = DVec3::new(s.x, s.y, s.z);
        let q = tect.query(dir);

        // Integer fields: exact match
        if q.plate_id != s.plate_id {
            failures.push(format!(
                "  tect[{i}] ({x:.6},{y:.6},{z:.6}): plate_id expected {}, got {}",
                s.plate_id, q.plate_id, x=s.x, y=s.y, z=s.z
            ));
        }
        if q.neighbor_id != s.neighbor_id {
            failures.push(format!(
                "  tect[{i}] ({x:.6},{y:.6},{z:.6}): neighbor_id expected {}, got {}",
                s.neighbor_id, q.neighbor_id, x=s.x, y=s.y, z=s.z
            ));
        }

        // Scalar fields: < 1e-9
        let check = |name: &str, exp: f64, act: f64| -> Option<String> {
            let err = (act - exp).abs();
            if err > TECT_TOL {
                Some(format!(
                    "  tect[{i}] ({x:.6},{y:.6},{z:.6}) {name}: expected {exp:.17e}, got {act:.17e}, err={err:.3e}",
                    x=s.x, y=s.y, z=s.z
                ))
            } else { None }
        };

        if let Some(f) = check("boundary_dist", s.boundary_dist, q.boundary_dist)    { failures.push(f); }
        if let Some(f) = check("convergence",   s.convergence,   q.convergence)       { failures.push(f); }
        if let Some(f) = check("shear",         s.shear,         q.shear)             { failures.push(f); }
        if let Some(f) = check("crust_dist",    s.crust_dist,    q.crust_dist)        { failures.push(f); }
        if let Some(f) = check("paleo_dist",    s.paleo_dist,    q.paleo_dist)        { failures.push(f); }
        if let Some(f) = check("other_crust_dist", s.other_crust_dist, q.other_crust_dist) { failures.push(f); }
    }

    if !failures.is_empty() {
        panic!(
            "FAIL: Tectonics::query diverged from golden ({} field failures over {} samples):\n{}",
            failures.len(), g.tectonics_samples.len(),
            failures.join("\n")
        );
    }
    println!("PASS: Tectonics::query — {} samples within {TECT_TOL:.0e}", g.tectonics_samples.len());
}

// ---------------------------------------------------------------------------
// E. TectonicHeightField::height — additive-octave LOD invariant
// ---------------------------------------------------------------------------

#[test]
fn golden_height_and_lod_invariant() {
    let g = load_golden();
    let p = &g.params;

    let hf = TectonicHeightField::new(TectonicHeightFieldParams {
        seed:              p.seed,
        plate_count:       p.plate_count,
        arc_density:       p.arc_density,
        hotspot_count:     p.hotspot_count,
        hotspot_intensity: p.hotspot_intensity,
        climate: ClimateParams {
            seed:           p.seed,
            base_temp:      p.base_temp,
            atmosphere:     p.atmosphere,
            band_count:     p.band_count,
            axial_tilt_rad: p.axial_tilt_deg.to_radians(),
            redistribution: None,
            greenhouse:     None,
            lapse_rate:     None,
        },
    });

    let mut failures = Vec::new();

    for (i, s) in g.height_samples.iter().enumerate() {
        let dir = DVec3::new(s.x, s.y, s.z);
        let actual = hf.height(dir, s.level);
        let err = (actual - s.value).abs();
        if err > HEIGHT_TOL {
            failures.push(format!(
                "  height[{i}] ({x:.6},{y:.6},{z:.6}) level={lv}: expected {exp:.17e}, got {act:.17e}, err={err:.3e}",
                x=s.x, y=s.y, z=s.z, lv=s.level,
                exp=s.value, act=actual,
            ));
        }
    }

    if !failures.is_empty() {
        panic!(
            "FAIL: TectonicHeightField::height diverged from golden ({}/{} vectors):\n{}",
            failures.len(), g.height_samples.len(),
            failures.join("\n")
        );
    }

    // Additional LOD invariant check from the golden itself:
    // For each spatial position (same x,y,z), levels 0 and 4 share the same
    // 6 base FBM octaves — so height(level=4) - height(level=0) should be ≤ 0.04
    // (at most one extra fbm octave amplitude: 0.5^6/MAX_AMP_FBM6 ≈ 0.016 * TECT_DETAIL_FBM_BASE ≈ 0.0016).
    // We verify it also holds in the goldens (catching any TS-side LOD drift).
    let level_groups: Vec<_> = g.height_samples.chunks(4).collect(); // 4 levels per dir
    let mut lod_failures = Vec::new();
    for (gi, group) in level_groups.iter().enumerate() {
        if group.len() < 2 { continue; }
        let h0 = group[0].value; // level 0
        let h4 = group[1].value; // level 4
        let diff = (h4 - h0).abs();
        if diff > 0.04 {
            lod_failures.push(format!(
                "  LOD invariant failed at dir[{gi}] ({x:.6},{y:.6},{z:.6}): |h(lv=4)-h(lv=0)|={diff:.4} > 0.04",
                x=group[0].x, y=group[0].y, z=group[0].z,
            ));
        }
    }
    if !lod_failures.is_empty() {
        panic!("FAIL: LOD additive-octave invariant violated in GOLDEN data ({} dirs):\n{}",
            lod_failures.len(), lod_failures.join("\n"));
    }

    println!("PASS: TectonicHeightField::height — {} vectors within {HEIGHT_TOL:.0e}", g.height_samples.len());
    println!("PASS: LOD additive-octave invariant — {} position groups", level_groups.len());
}
